/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AirSpaceNFT } from "./AirSpaceNFT";
export type { AirSpaceTransfer } from "./AirSpaceTransfer";
