/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AirSpaceNFT__factory } from "./AirSpaceNFT__factory";
export { AirSpaceTransfer__factory } from "./AirSpaceTransfer__factory";
